### ISSUE TITLE
Communication Protocol

### ISSUE THREAD

**Issue by A5rocks** [repl-it-discord/carnival#1]
So, ~~we can't agree on the protocol to use~~ we should use a combination of websockets and http.

What I mean by that is that every game gets to make their server. Carnival gets to act as a central hub, for getting to those games, and maybe a proxy (if that's what you want).

Example Carnival Interaction: 
```
GET /games/{game_id}
... Headers ...

Response from server: {game_url}
```
Then you connect to the game, and continue from there.

Though this may make making a multi-game client a challenge, due to different protocols, it is still possible if we make every game be required to respond with the protocol they are using to a get request to `{game_server}/protocol/raw`.

This would require making a few more choices, but allow much more freedom, allowing an easy game-making (http requests), and an easy event system (websockets).

**Comment by Zwork101** [comment]
It's been decided. We'll use HTTP for client <-> server communications, and pipes for server <-> games.

**Comment by 88pawankumarjha** [comment]
Is this only for python?

**Comment by EanKeen** [comment]
@88pawankumarjha So concerning creating game servers and game clients there really is no restriction. We're thinking it should support communication over HTTP, which is not an issue at all. Additionally, we're thinking about using an authorization protocol called [OpenID Connect](https://openid.net/connect/) (so we can keep track of the same users over different carnival games), but this is totally optional for carnival game developers. If we do go this route of using OpenID Connect we're going to make it easier for carnival game developers - we'll give code samples to integrate with our authentication systems to make it much easier. We're still hammering out the fine details at the issue [here](https://github.com/repl-it-discord/carnival/issues/2)
