### ISSUE TITLE
SQL Injection

### ISSUE THREAD

**Issue by apoorvsingal** [repl-it-discord/carnival#10]
The database at the server is prone to sql injection. The data from the client is neither checked if it's malicious nor is it escaped properly to make it work as expected.

**Comment by TheDrone7** [comment]
Please provide some links for reference for the solution as well if possible. I don't have a lot of time for research atm.
Thank you.

**Comment by apoorvsingal** [comment]
Check out https://www.postgresql.org/docs/9.2/sql-syntax-lexical.html for escaping in sql or  https://node-postgres.com/features/queries for nodejs specific info.

**Comment by TheDrone7** [comment]
Thanks a lot, I'll look into the issue and solve it ASAP.

**Comment by TheDrone7** [comment]
It's been fixed, thanks again! I'll wait for 3 days before closing this issue to wait for you to check if everything is fine now.

**Comment by TheDrone7** [comment]
Since there was no known issue reported in the given 3 days, I am now closing this issue.
